### ISSUE TITLE
Correct Settings

### ISSUE THREAD

**Issue by digitaledge-git** [zeyad-mansour/Lunar#13]
Hi, 
i was just testing the aimbot with 14.3 x/y and 100 (100%) target sensivity settings. The result was not that great so far. Im just wondering if you could recomment settings that might work better.

Since im normally playing with controller, i would like to know how the bot could might be optimized to support that. 

Kind Regards
Stefan

**Comment by zeyad-mansour** [comment]
Any sensitivity should work, but higher sensitivities are marginally faster because [interpolate_coordinates_from_center](https://github.com/zeyad-mansour/Lunar/blob/960a34ae4dece55d218fd03d8df2613fc72bc473/lib/aimbot.py#L134) needs to work less.

**Comment by zeyad-mansour** [comment]
Try pulling the repo again. I have updated it so that the aimbot only works when your player is targeting or scoping in. 

Understand that there are still are several issues with the aimbot and improvements that I am working on — see [future updates](https://github.com/zeyad-mansour/Lunar#future-updates).
