### ISSUE TITLE
[Suggestion] Alternative Mouse library

### ISSUE THREAD

**Issue by matias-kovero** [zeyad-mansour/Lunar#57]
Hi,
just created my first object detection for an aimbot using YOLOv5 - and while placing github tags stumbled on your code.

As I struggled as well with mouse latency at the start - I resorted to [Interception](https://github.com/oblitum/Interception) Driver.
Yes you will need to install an additional driver to your computer - but you will have zero latency - and more control.

It will be an MITM between your mouse buffer and OS - so no VIRTUAL_MOUSE flags are set, thus games anti-cheat can't really detect external mouse movement - as you can tamper the movement your physical mouse is sending.

With a quick glance of your code, it seems you aren't using any multiprocessing nor threading? This could potentially speed things up a bit.

If you want to check my code, feel free: [https://github.com/matias-kovero/ObjectDetection](https://github.com/matias-kovero/ObjectDetection)

**Comment by zeyad-mansour** [comment]
Thanks for the suggestions! Both are very valid.

I'm already aware of these improvements that can be made, and I've actually implemented them in a private C++ project that I've been working on.  However, I've decided against releasing it due to several reasons, and as described in the README, I'm no longer actively working on this repository.

Btw: nice project!
